version: '2'
services:
  etcd:
    image: gcr.io/google_containers/etcd-amd64:3.1.12
    container_name: etcd
    hostname: etcd
    volumes:
    - /etc/ssl/certs:/etc/ssl/certs
    - /var/lib/etcd-cluster:/var/lib/etcd
    ports:
    - 4001:4001
    - 2380:2380
    - 2379:2379
    restart: always
    command: ["sh", "-c", "etcd --name=etcd1 \
      --advertise-client-urls=http://172.26.133.21:2379,http://172.26.133.21:4001 \
      --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001 \
      --initial-advertise-peer-urls=http://172.26.133.21:2380 \
      --listen-peer-urls=http://0.0.0.0:2380 \
      --initial-cluster-token=9489bf68bdfe1b9ae037d6fd9e7efefd \
      --initial-cluster=etcd1=http://172.26.133.21:2380,etcd2=http://172.26.133.22:2380,etcd3=http://172.26.133.23:2380,etcd4=http://172.26.133.24:2380,etcd5=http://172.26.133.25:2380 \
      --initial-cluster-state=new \
      --auto-tls \
      --peer-auto-tls \
      --data-dir=/var/lib/etcd"]
